siteTitle = 'Món Ngon Bình Dương'
siteDescr = 'Teen Bình Dương, Teen Việt Nam.'
siteDescription = "Cùng tới với chúng tôi, vui vẻ cùng 4teenviet."
siteUrl = "http://monngonbinhduong.com/"
siteBandcampUrl = 'http://monngonbinhduong.com/'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/M%C3%B3n-Ngon-B%C3%ACnh-D%C6%B0%C6%A1ng-185286918690182/'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/nihon_ne'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/binhduongbuy'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
